@APBDTest_HostAddress = http://localhost:5149

#GET {{APBDTest_HostAddress}}/api/visits/14
#Accept: application/json

POST {{APBDTest_HostAddress}}/api/visits
Content-Type: application/json

{
  "visitId": 15,
  "clientId": 1,
  "mechanicLicenceNumber": "MECH-20230001",
  "services": [
    {
      "serviceName": "Oil Change",
      "serviceFee": 100
    },
    {
      "serviceName": "Brake Repair",
      "serviceFee": 280.00
    }
  ]
}

###
